# Generated by Django 5.0.6 on 2025-02-27 08:47

import company_app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('official_email', models.EmailField(max_length=254, unique=True, validators=[company_app.models.validate_official_email])),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Retail', 'Retail')], max_length=100)),
                ('number_of_employees', models.CharField(choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51-200', '51-200 Employees'), ('201-500', '201-500 Employees'), ('501+', '501+ Employees')], max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Enter a valid GST number.')])),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('pan_number', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Enter a valid PAN number.')])),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost_name', models.CharField(max_length=255)),
                ('jobpost_phoneno', models.CharField(max_length=255)),
                ('jobpost_email', models.CharField(max_length=255)),
                ('jobpost_designation', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_workplace', models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Other', 'Other'), ('Volunteer', 'Volunteer'), ('Internship', 'Internship')], max_length=255)),
                ('job_no_opening', models.CharField(max_length=255)),
                ('job_salary', models.CharField(max_length=255)),
                ('job_experience', models.CharField(blank=True, max_length=25)),
                ('job_skills', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company_app.company')),
            ],
        ),
    ]
