# Generated by Django 5.0.4 on 2025-03-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="unique_number",
            field=models.CharField(default="0", max_length=255, null=True),
        ),
    ]
