# Generated by Django 5.0.6 on 2025-02-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='unique_number',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
