# Generated by Django 5.0.6 on 2025-09-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_job_job_benefits_job_job_company_culture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='job_description',
        ),
    ]
