# Generated by Django 5.0.6 on 2025-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_rename_description_job_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_description',
        ),
        migrations.AddField(
            model_name='job',
            name='more_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
