# Generated by Django 5.0.4 on 2025-08-11 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_app", "0003_jobapplication_jobquestion_applicationanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="gst_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$",
                        "Enter a valid GST number.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="pan_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{5}[0-9]{4}[A-Z]{1}$", "Enter a valid PAN number."
                    )
                ],
            ),
        ),
    ]
