# Generated by Django 5.0.4 on 2025-08-30 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_app", "0004_alter_company_gst_number_alter_company_pan_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="unique_number",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
