# Generated by Django 5.0.4 on 2025-08-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_app", "0005_alter_job_unique_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="unique_number",
            field=models.CharField(default="0", max_length=255, null=True),
        ),
    ]
