# Generated by Django 5.0.4 on 2025-08-30 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company_app", "0008_job_unique_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="unique_number",
        ),
    ]
