# Generated by Django 5.0.4 on 2025-09-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_app", "0009_remove_job_unique_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("closed", "Closed"),
                ],
                default="active",
                max_length=255,
            ),
        ),
    ]
