# Generated by Django 5.0.6 on 2024-12-26 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('work_status', models.CharField(choices=[('experienced', 'Experienced'), ('fresher', 'Fresher')], max_length=20)),
                ('promotions', models.BooleanField(default=False)),
                ('seekerPreference', models.CharField(max_length=255, null=True)),
                ('seeker_skills', models.CharField(max_length=255, null=True)),
                ('profile_summary', models.TextField(max_length=555, null=True)),
                ('resume', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerCompetitiveExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('competitive_score', models.CharField(max_length=50)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker_app.seeker')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('TENTH', '10th'), ('TWELFTH', '12th'), ('DIPLOMA', 'Diploma'), ('GRADUATION', 'Graduation'), ('POSTGRADUATION', 'Postgraduation'), ('HIGHER_STUDIES', 'Higher Studies')], max_length=255)),
                ('institution', models.CharField(max_length=255, null=True)),
                ('year_of_starting', models.DateField(blank=True, null=True)),
                ('year_of_passing', models.DateField(blank=True, null=True)),
                ('marks', models.IntegerField(null=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker_app.seeker')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icompany_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker_app.seeker')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=255, null=True)),
                ('proficiency', models.CharField(choices=[('basic', 'Basic'), ('istermediate', 'Intermedicate'), ('advanced', 'Advanced')], max_length=255)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker_app.seeker')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker_app.seeker')),
            ],
        ),
    ]
