# Generated by Django 5.0.6 on 2024-12-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekercompetitiveexam',
            name='competitive_score',
            field=models.FloatField(),
        ),
    ]
