# Generated by Django 5.0.6 on 2024-12-27 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker_app', '0002_alter_seekercompetitiveexam_competitive_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerProfileEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_company_name', models.CharField(max_length=255)),
                ('employment_role', models.CharField(max_length=255)),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField(blank=True, null=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker_app.seeker')),
            ],
        ),
    ]
