# Generated by Django 5.0.6 on 2024-12-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker_app', '0003_seekerprofileemployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofileemployment',
            name='employment_company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seekerprofileemployment',
            name='employment_role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
