# Generated by Django 5.0.6 on 2024-12-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker_app', '0004_alter_seekerprofileemployment_employment_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekercompetitiveexam',
            name='competitive_score',
            field=models.FloatField(null=True),
        ),
    ]
