# Generated by Django 5.0.6 on 2024-12-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker_app', '0005_alter_seekercompetitiveexam_competitive_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerAcademicAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.TextField(null=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker_app.seeker')),
            ],
        ),
    ]
