# Generated by Django 5.0.4 on 2025-07-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seeker_app", "0006_seekeracademicachievement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seekerprofileemployment",
            name="employment_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seekerproject",
            name="project_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
