# Generated by Django 5.0.4 on 2025-07-30 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "seeker_app",
            "0007_alter_seekerprofileemployment_employment_start_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="seekerinternship",
            old_name="icompany_name",
            new_name="company_name",
        ),
    ]
