# Generated by Django 5.0.4 on 2025-08-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seeker_app", "0008_rename_icompany_name_seekerinternship_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seekereducation",
            name="marks",
            field=models.FloatField(null=True),
        ),
    ]
