# Generated by Django 5.0.6 on 2025-08-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker_app', '0009_alter_seekereducation_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='profile_summary',
            field=models.TextField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='seekerPreference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='seeker_skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
