# Generated by Django 5.0.4 on 2025-08-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "seeker_app",
            "0010_alter_seeker_profile_summary_alter_seeker_resume_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="seeker",
            name="seeker_skills",
        ),
        migrations.AddField(
            model_name="seeker",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="seekers", to="seeker_app.skill"
            ),
        ),
    ]
